# Generated by Django 5.2.9 on 2025-12-10 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LecturaCuentakm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_lectura', models.CharField(choices=[('inicio_semana', 'Inicio de semana'), ('fin_semana', 'Fin de semana')], max_length=20)),
                ('kilometros', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='lecturas/')),
                ('semana', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecturas.comercial')),
            ],
        ),
    ]
