# Generated by Django 5.2.9 on 2025-12-10 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturacuentakm',
            options={'ordering': ['-anio', '-semana', '-created_at']},
        ),
        migrations.RenameField(
            model_name='lecturacuentakm',
            old_name='fecha_hora',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='lecturacuentakm',
            name='fin_fuera_de_plazo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lecturacuentakm',
            name='anio',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lecturacuentakm',
            name='comercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='lecturas.comercial'),
        ),
        migrations.AlterField(
            model_name='lecturacuentakm',
            name='kilometros',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecturacuentakm',
            name='semana',
            field=models.PositiveIntegerField(),
        ),
    ]
