# Generated by Django 5.2.9 on 2025-12-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturas', '0002_alter_lecturacuentakm_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturacuentakm',
            name='inicio_no_cuadra',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comercial',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='lecturacuentakm',
            name='anio',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='lecturacuentakm',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='lecturas/'),
        ),
        migrations.AlterField(
            model_name='lecturacuentakm',
            name='semana',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddIndex(
            model_name='lecturacuentakm',
            index=models.Index(fields=['comercial', 'anio', 'semana', 'tipo_lectura'], name='lecturas_le_comerci_493087_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturacuentakm',
            index=models.Index(fields=['created_at'], name='lecturas_le_created_31e4f8_idx'),
        ),
    ]
